apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-app
    spec:
      containers:
      - name: argocd-app-container
        image: jeongsujin/app-with-argocd:c28bf6a88976f886ba214cc16f949239cf29701c
       #imagePullPolicy: Always
        ports:
          - protocol: TCP
            containerPort: 8080
